### ISSUE TITLE
First Steps

### ISSUE THREAD

**Issue by scivarolo** [scivarolo/barkeeper#23]
- [x] Add react-router-dom, reactstrap, bootstrap, and node-sass to project
- [x] Setup API module for base API calls to local database #24
- [x] Setup initial routes #2
- [x] Setup user authentication and login/registration views #1
